package(default_visibility = ["//visibility:public"])
load("@rules_gcc_arm_none_eabi//:gen.bzl", "gen_bin", "gen_hex", "gen_asm")

cc_library(
    name = "example",
    srcs = [
        "lib.c",
        "lib.cc",
    ],
)
